prompt <h2>DBA Users </h2>

ALTER SESSION SET NLS_DATE_FORMAT ='YYYY/MM/DD HH24:MI';

select /* axiome */
     X.USERNAME,
     X.USER_ID,
     X.ACCOUNT_STATUS,
     X.LOCK_DATE,
     X.EXPIRY_DATE,
     X.DEFAULT_TABLESPACE,
     X.TEMPORARY_TABLESPACE,
     X.CREATED,
     X.PROFILE,
     X.PASSWORD_VERSIONS
FROM
     DBA_USERS X
ORDER BY
     X.USERNAME;