prompt <h2>DBA Users</h2>

ALTER SESSION SET NLS_DATE_FORMAT ='YYYY/MM/DD HH24:MI';

select /* db-html-report */
     USERNAME,
     USER_ID,
     ACCOUNT_STATUS,
     LOCK_DATE,
     EXPIRY_DATE,
     DEFAULT_TABLESPACE,
     TEMPORARY_TABLESPACE,
     CREATED,
     PROFILE,
     PASSWORD_VERSIONS
FROM
     DBA_USERS
ORDER BY
     USERNAME;