prompt <h2>Les objets par utilisateur</h2>

select /* db-html-report */
  *
FROM
  (
    SELECT
      OWNER,
      OBJECT_TYPE,
      COUNT(*)    AS OBJECT_COUNT
    FROM
      DBA_OBJECTS
    WHERE
      OWNER NOT IN ('ANONYMOUS', 'APEX_180200', 'APEX_INSTANCE_ADMIN_USER', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'AUDSYS', 'CTXSYS', 'DBSFWUSER', 'DBSNMP', 'DIP', 'DVF', 'DVSYS', 'FLOWS_FILES', 'GGSYS', 'GSMADMIN_INTERNAL', 'GSMCATUSER', 'GSMUSER', 'LBACSYS', 'MDDATA', 'MDSYS', 'OJVMSYS', 'OLAPSYS', 'ORACLE_OCM', 'ORDDATA', 'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'REMOTE_SCHEDULER_AGENT', 'SI_INFORMTN_SCHEMA', 'SYS', 'SYS$UMF', 'SYSBACKUP', 'SYSDG', 'SYSKM', 'SYSRAC', 'SYSTEM', 'WMSYS', 'XDB', 'XS$NULL')
    GROUP BY
      OWNER,
      OBJECT_TYPE
    ORDER BY
      OWNER,
      OBJECT_TYPE
  ) PIVOT ( MAX(OBJECT_COUNT) FOR OBJECT_TYPE IN ( 'TABLE',
  'VIEW',
  'INDEX',
  'FUNCTION',
  'LOB',
  'PACKAGE',
  'PROCEDURE',
  'TRIGGER',
  'SYNONYM' ) )
ORDER BY
  OWNER;