prompt <h2>Les options utilisée (à partir de DBA_FEATURE_USAGE_STATISTICS): </h2>

ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD HH24:MI:SS';

select /* db-html-report */
    NAME,
    LAST_USAGE_DATE,
    DETECTED_USAGES,
    DESCRIPTION
FROM
    DBA_FEATURE_USAGE_STATISTICS
WHERE
    DETECTED_USAGES>0
ORDER BY
    NAME;