prompt <h2>Les options utilisée (à partir de DBA_FEATURE_USAGE_STATISTICS): </h2>

select NAME, TO_CHAR(LAST_USAGE_DATE, 'DD/MM/YYYY HH24:MI') LAST_USAGE_DATE, DETECTED_USAGES, DESCRIPTION from DBA_FEATURE_USAGE_STATISTICS
where DETECTED_USAGES>0
order by NAME;